import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const html = await readFile(resolve(root, "index.html"), "utf8");
const app = await readFile(resolve(root, "src/app.js"), "utf8");
const css = await readFile(resolve(root, "styles.css"), "utf8");

test("trimfönstret har 20 minuter som redigerbart standardvärde", () => {
  assert.match(html, /id="trimWindowDurationInput"[^>]*value="20:00\.000"/);
  assert.match(html, /id="applyWindowFromStartButton"/);
  assert.match(html, /id="applyWindowAtPlayheadButton"/);
  assert.match(html, /id="applyWindowToEndButton"/);
  assert.match(app, /trimWindowSeconds:\s*20 \* 60/);
  assert.match(app, /function applyTrimWindow\(anchor\)/);
  assert.match(app, /Math\.min\(state\.trimWindowSeconds, sourceDuration\)/);
  assert.match(app, /trimWindowSeconds: state\.trimWindowSeconds/);
  for (const id of ["trimHud", "trimHudRange", "trimHudDuration", "exportTrimCanvas", "analysisTimeAxis", "centerWindowAtPlayheadButton"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(html, /data-move-window="-60"/);
  assert.match(html, /data-move-window="60"/);
  assert.match(html, /data-fit-selection/);
  assert.match(html, /data-expand-timeline="analysisTimelineCard"/);
  assert.match(html, /data-expand-timeline="trimTimelineCard"/);
  assert.doesNotMatch(html, /<div class="time-axis"[^>]*><span>00:00/);
  assert.match(app, /function moveTrimWindow\(deltaSeconds/);
  assert.match(app, /function setTrimWindowPosition\(startSeconds/);
  assert.match(app, /const windowLength = Math\.min\(selectionDurationSeconds\(\), sourceDuration\)/);
  assert.match(app, /function fitTrimSelection\(\)/);
  assert.match(app, /function showTrimWindow\(\)/);
  assert.match(app, /data-fit-selection[\s\S]*showTrimWindow/);
  assert.match(app, /function activateTrimAudition/);
  assert.match(app, /state\.playback\.currentSeconds = state\.trim\.startSeconds/);
  assert.match(app, /if \(gesture\.target === "window"\) activateTrimAudition\(\)/);
  assert.match(html, /Visa och flytta trimfönstret/);
  assert.match(app, /function toggleTimelineExpansion\(cardId/);
  assert.match(html, /id="toggleTrimEditorButton"[^>]*>Lås upp trimfönstret/);
  assert.match(html, /id="applyTrimSelectionButton"[^>]*disabled>Trimma bort utanför A\/B/);
  assert.match(html, /id="revertTrimSelectionButton"[^>]*disabled>Återgå till aktivt urval/);
  assert.match(app, /trimEditor:\s*\{\s*unlocked:\s*false,\s*applied:\s*true/);
  assert.match(app, /function markTrimCandidateChanged/);
  assert.match(app, /function applyTrimSelection/);
  assert.match(app, /function revertTrimSelection/);
  assert.match(app, /if \(!state\.trimEditor\.unlocked\) return false/);
  assert.match(app, /state\.trimEditor\.applied = true;[\s\S]*markEditChanged\("trim-selection-applied"\)/);
  assert.match(app, /Tillämpa trimfönstret eller återgå till det aktiva urvalet före export/);
  assert.match(css, /\.trim-editor-state\.is-unlocked/);
  assert.match(css, /\.trim-timeline-card\.is-trim-unlocked/);
  assert.match(html, /id="globalPlayer"[\s\S]*id="transportSeek"/);
  assert.ok(html.indexOf('id="globalPlayer"') < html.indexOf('id="mainContent"'), "spelaren ska ligga utanför flikpanelerna");
  assert.equal((html.match(/id="audioPlayer"/g) || []).length, 1);
  assert.match(app, /function seekPlayback\(seconds/);
  assert.match(app, /requestAnimationFrame\(tick\)/);
  assert.match(app, /audioContext\.state !== "running"/);
  const playbackStart = app.match(/async function startPlayback\(\)[\s\S]*?\n}\n\nfunction seekPlayback/)?.[0] || "";
  assert.match(playbackStart, /graphReady = await ensureAudioGraph\(\)/);
  assert.ok(playbackStart.indexOf("graphReady = await ensureAudioGraph()") < playbackStart.indexOf("await elements.audio.play()"), "säker monitorgraf ska vara klar innan uppspelningen startar");
  assert.match(playbackStart, /safetyRequired && !graphReady/);
  assert.match(app, /addEventListener\("error"/);
  assert.match(html, /data-peak-ceiling="-1"/);
  assert.match(html, /data-peak-ceiling="-2"/);
  assert.match(html, /data-peak-ceiling="-3"/);
  assert.match(app, /function applyNegativePeakCeiling/);
  assert.match(app, /const reduction = Math\.min\(0, target - peak\)/);
  assert.match(html, /id="gainNumber"[^>]*min="-60"/);
  assert.equal((html.match(/data-diagram-action="toggle"/g) || []).length, 2);
  assert.match(html, /data-diagram-action="play-visible"/);
  assert.match(html, /data-diagram-action="play-selection"/);
  assert.match(app, /\$\$\('\[data-diagram-time\]'\)/);
  assert.match(html, /id="floatOverrangeRegions"/);
  assert.match(app, /function renderFloatOverrangeMap/);
  assert.match(app, /floatsamplingar över 0 dBFS bevarades i filen/);
  for (const id of ["peakGuideStatus", "peakGuideMeasured", "peakGuideMeaning", "peakGuideClipping", "peakGuideExport", "playHighestPeakButton", "showFloatPeaksButton", "openPeakStudyButton", "openPeakSafetyButton", "preservePeakOriginalButton", "peakStudyDialog", "peakStudyChannels", "peakStudyProblems", "peakStudyScenarios"]) assert.match(html, new RegExp(`id="${id}"`));
  for (const id of ["peakCategoryFloatStatus", "peakCategoryFloatText", "peakCategoryDigitalStatus", "peakCategoryDigitalText", "peakCategoryAnalogStatus", "peakCategoryAnalogText", "peakCategoryDeliveryStatus", "peakCategoryDeliveryText"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(app, /function renderPeakGuide\(\)/);
  assert.match(app, /function renderPeakCategories/);
  assert.match(html, /Bevarad floatnivå/);
  assert.match(app, /Den färdiga filen kan inte ensam visa säkert om mikrofon, försteg eller omvandlare överbelastades/);
  assert.match(app, /Sänk före PCM/);
  assert.match(app, /Granska leveransmarginal/);
  assert.match(app, /Pass för testet/);
  assert.match(app, /Vissa uppspelnings-, heltals- eller konverteringsled kan mätta/);
  assert.match(app, /inte bevis för att mikrofon eller försteg var fria från distorsion/);
  assert.match(app, /En möjlig platå hittades\. Det är en heuristisk varning, inte en säker klippdiagnos/);
  assert.match(app, /Ingen limiter, kompressor eller dold toppsänkning används/);
  assert.match(app, /elements\.playHighestPeak\.addEventListener/);
  assert.match(app, /elements\.openPeakSafety\.addEventListener/);
  assert.match(app, /function renderPeakStudy\(\)/);
  assert.match(app, /data-peak-channel-time/);
  assert.match(app, /data-peak-study-target/);
  assert.match(app, /Jämförelsen bygger på det aktuella beräknade exporturvalet/);
  assert.match(css, /\.peak-guide-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2/s);
  assert.match(css, /\.peak-category-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2/s);
  assert.match(css, /\.peak-study-dialog\s*\{/);
  for (const id of ["openFullAnalysisButton", "fullAnalysisDialog", "fullAnalysisContent"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(app, /function renderFullAnalysis\(\)/);
  assert.match(app, /Olika typer av toppar och klippning/);
  assert.match(app, /Vad analysen inte kan avgöra/);
  assert.match(app, /data-full-analysis-play/);
  assert.match(css, /\.full-analysis-dialog/);
  for (const id of ["modeStatusOpen", "modeStatusAnalyze", "modeStatusTrim", "modeStatusPreflight", "modeStatusExport", "analysisModuleBoard", "openFullAnalysisBoardButton", "runPreflightButton", "preflightProcessStatus", "preflightOutcomeStatus", "monitorSafetyStatus"]) assert.match(html, new RegExp(`id="${id}"`));
  for (const moduleName of ["integrity", "peaks", "loudness", "dynamics", "stereo", "review"]) assert.match(html, new RegExp(`data-analysis-module="${moduleName}"`));
  assert.match(app, /function renderWorkflowStatus\(\)/);
  assert.match(app, /function renderPreflightPanel\(\)/);
  assert.match(app, /function preflightAnalysisStatus\(\)/);
  assert.match(app, /sourceIntegrity\.state === "stop"/);
  assert.match(app, /True Peak kunde inte beräknas/);
  assert.match(html, /id="preflightContinueButton"[^>]*disabled/);
  assert.match(html, /class="mode-tab is-active is-prestage"/);
  assert.match(html, /<span class="step-number">Fil<\/span>[\s\S]*<span class="step-number">1<\/span>[\s\S]*<span class="step-number">4<\/span>/);
  assert.match(app, /function monitorSafetyForPreview\(\)/);
  assert.match(app, /Säker medhörning kunde inte starta/);
  assert.match(app, /function renderAnalysisModuleBoard\(\)/);
  assert.match(app, /function openFullAnalysisAt\(/);
  assert.match(app, /data-full-analysis-marker/);
  assert.match(app, /Öppna i markörgranskning/);
  assert.match(app, /markerButton[\s\S]*setMode\("analyze"\)[\s\S]*data-marker-review/);
  assert.match(app, /Ingen klippindikation hittades av dessa tester/);
  assert.doesNotMatch(app, /Rapporterade klippta samplingar/);
  assert.match(css, /\.analysis-module-board\s*\{/);
  assert.match(css, /\.analysis-module-card\[data-state="stop"\]/);
  assert.match(css, /\.peak-category-grid header span\[data-state="info"\]/);
  for (const id of ["openFullAnalysisButton", "fullAnalysisDialog", "fullAnalysisContent", "openLocalPeakWorkshopButton", "localPeakWorkshopDialog", "localPeakRegionList", "calculateLocalPeakResultButton"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(app, /function renderFullAnalysis\(\)/);
  assert.match(app, /Olika typer av toppar och klippning/);
  assert.match(app, /Analog överstyrning/);
  assert.match(app, /Komprimerade format kan också skapa nya toppar/);
  assert.match(app, /function renderLocalPeakWorkshop/);
  assert.match(app, /localGainRegions: activeLocalGainRegions/);
  assert.match(css, /\.full-analysis-dialog,\s*\.local-peak-dialog\s*\{/);
  for (const id of ["openLocalPeakWorkshopButton", "localPeakWorkshopDialog", "addHighestPeakRegionButton", "addAllFloatPeakRegionsButton", "addPeakAtPlayheadButton", "undoLocalPeakButton", "redoLocalPeakButton", "bypassLocalPeaksToggle", "calculateLocalPeakResultButton", "localPeakRegionList"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(app, /from "\.\/local-gain\.js"/);
  assert.match(app, /function renderLocalPeakWorkshop/);
  assert.match(app, /elements\.openLocalPeakWorkshop\.addEventListener/);
  assert.equal((app.match(/elements\.openLocalPeakWorkshop\.addEventListener/g) || []).length, 1);
  assert.equal((app.match(/elements\.addHighestPeakRegion\.addEventListener/g) || []).length, 1);
  assert.equal((app.match(/elements\.undoLocalPeak\.addEventListener/g) || []).length, 1);
  assert.equal((app.match(/elements\.calculateLocalPeakResult\.addEventListener/g) || []).length, 1);
  assert.equal((app.match(/data-full-action="peak-workshop"/g) || []).length, 1);
  assert.match(app, /localGainRegions: activeLocalGainRegions\(\)/);
  assert.match(app, /localGainRegions: activeLocalGainRegions\(\)\.map/);
  assert.match(app, /data-local-action="preview"/);
  assert.match(css, /\.local-peak-dialog\s*\{/);
  assert.match(html, /id="expandObservationsButton"/);
  assert.match(html, /id="observationsDialog"/);
  assert.match(app, /function observationCards/);
  assert.match(app, /hadMultiplePointers/);
  assert.match(app, /!timelineGesture\?\.moved && !hadMultiplePointers/);
});

test("iPadflödet har fyra arbetssteg, en huvudåtgärd och fokuserade moduler", () => {
  const workflowNav = html.match(/<nav class="mode-nav" id="workflowNav"[\s\S]*?<\/nav>/)?.[0] || "";
  assert.match(workflowNav, /id="workflowNav"[^>]*hidden/);
  assert.equal((workflowNav.match(/class="mode-tab" data-mode="(?:analyze|trim|preflight|export)"/g) || []).length, 4);
  assert.match(workflowNav, /data-mode="open"[^>]*hidden/);
  for (const id of ["workflowActionDock", "workflowPrimaryAction", "workspaceModuleDialog", "sessionPlayButton", "sessionSafetyStatus"]) assert.match(html, new RegExp(`id="${id}"`));
  for (const target of ["assessmentContext", "analysisTimelineCard,canvasTextAlternative", "deepMeasurements", "analysisInspector", "trimTimelineCard,trimWindowCard,trimControlGrid", "fadeModule", "gainModule,recommendationWorkbench", "trimAuditionModule,auditionStatus,monitorModule", "metadataModule", "publicationModule"]) assert.match(html, new RegExp(`data-workspace-target="${target}"`));
  assert.match(html, /data-analysis-module="rumble"/);
  assert.ok(html.indexOf('id="exportAudioButton"') < html.indexOf('id="metadataModule"'), "exportåtgärden ska ligga före metadata i DOM-ordningen");
  assert.equal((html.match(/id="exportAudioButton"/g) || []).length, 1);
  assert.match(app, /function workflowStepModel\(\)/);
  assert.match(app, /function renderWorkflowActionDock\(\)/);
  assert.match(app, /function openWorkspaceModule\(invoker\)/);
  assert.match(app, /document\.createComment\(`restore-/);
  assert.match(app, /invoker\?\.focus\?\./);
  assert.match(css, /\.mode-nav\s*\{[^}]*grid-template-columns:\s*repeat\(4/s);
  assert.match(css, /\[data-panel="analyze"\] \.heading-actions,[\s\S]*\.preflight-actions #preflightContinueButton \{ display: none; \}/);
  assert.match(css, /@media \(max-width: 1100px\)[\s\S]*\.workspace-module-dialog,[\s\S]*width: 100vw;[\s\S]*height: 100dvh;/);
  assert.match(css, /\.session-transport #sessionTime \{ display: none; \}/);
  assert.match(css, /\.session-transport \.session-safety \{ display: block;/);
  assert.match(app, /if \(!state\.analysis\) \{[\s\S]*Uppspelningen är låst tills toppnivån är känd/);
  assert.match(app, /\[data-monitor-safety-mirror\]/);
  assert.match(html, /data-module-transport-action="toggle"/);
  const recommendationsHandler = app.match(/elements\.openRecommendations\.addEventListener[\s\S]*?\n  \}\);/)?.[0] || "";
  const peakSafetyHandler = app.match(/elements\.openPeakSafety\.addEventListener[\s\S]*?\n  \}\);/)?.[0] || "";
  assert.doesNotMatch(recommendationsHandler, /requestRegionAnalysis/);
  assert.doesNotMatch(peakSafetyHandler, /requestRegionAnalysis/);
  const projectRestore = app.match(/async function applyPendingProjectToFile\(\)[\s\S]*?\n}\n\nfunction reportInput/)?.[0] || "";
  assert.doesNotMatch(projectRestore, /requestRegionAnalysis\(\)|startAnalysis\(\)/);
  assert.match(projectRestore, /if \(!monitorSafetyForPreview\(\)\.ready\)/);
  assert.match(projectRestore, /\$\$\('dialog\[open\]'\)/);
  assert.match(projectRestore, /setMode\("analyze"\)/);
});

test("säker medhörning kräver aktuell toppanalys och takbyte ogiltigförklarar verifiering", () => {
  assert.match(app, /analysisPlaybackSource:\s*"none"/);
  assert.match(app, /state\.analysisPlaybackSource = "current-session";[\s\S]*?renderMonitorSafetyStatus\(\);/);
  assert.match(app, /state\.analysisPlaybackSource = state\.analysis \? "restored-project" : "none"/);
  assert.match(app, /function monitorSafetyForPreview\(\)[\s\S]*monitorSafetyDecision\([\s\S]*trustedSource: state\.analysisPlaybackSource === "current-session"/);
  const playbackStart = app.match(/async function startPlayback\(\)[\s\S]*?\n}\n\nfunction seekPlayback/)?.[0] || "";
  assert.match(playbackStart, /const playbackSafety = monitorSafetyForPreview\(\)/);
  assert.match(playbackStart, /if \(!playbackSafety\.ready\)/);
  const invalidator = app.match(/function invalidatePreflightAndVerification\([\s\S]*?\n}\n\nfunction markEditChanged/)?.[0] || "";
  for (const pattern of [/state\.regionAnalysis = null/, /state\.verifiedExport = null/, /state\.lastExportReport = null/, /activeExportJob/, /state\.jobs\.export = null/, /verifiedMeasureStatus\.textContent = verifiedMessage/]) assert.match(invalidator, pattern);
  assert.match(invalidator, /exportWorker\?\.postMessage\(\{ type: "cancel"/);
  assert.match(invalidator, /\["running", "cancelling", "complete"\]\.includes\(state\.exportStatus\)/);
  const ceilingHandler = app.match(/elements\.localPeakCeiling\.addEventListener\("change"[\s\S]*?\n  \}\);/)?.[0] || "";
  assert.match(ceilingHandler, /invalidatePreflightAndVerification/);
  assert.match(ceilingHandler, /Ogiltig efter ändrat leveranstak/);
  const setMode = app.match(/function setMode\(mode, options = \{\}\)[\s\S]*?\n}\n\nfunction runWorkflowPrimaryAction/)?.[0] || "";
  assert.match(setMode, /\["trim", "preflight", "export"\]\.includes\(mode\) && !monitorSafetyForPreview\(\)\.ready/);
  assert.match(setMode, /setMode\("analyze", options\)/);
  const playbackAvailability = app.match(/function syncPlaybackAvailability\(\)[\s\S]*?\n}/)?.[0] || "";
  assert.match(playbackAvailability, /monitorSafetyForPreview\(\)\.ready/);
  for (const element of ["sessionPlayButton", "playButton", "transportSeek"]) assert.match(playbackAvailability, new RegExp(`elements\\.${element}.*disabled = !ready`));
  const playbackPosition = app.match(/function syncPlaybackPosition\([\s\S]*?\n}\n\nfunction stopPlaybackClock/)?.[0] || "";
  const safetyRenderer = app.match(/function renderMonitorSafetyStatus\(\)[\s\S]*?\n}\n\nfunction schedulePreviewEnvelope/)?.[0] || "";
  assert.match(playbackPosition, /syncPlaybackAvailability\(\)/);
  assert.match(safetyRenderer, /syncPlaybackAvailability\(\)/);
  const safetyDecision = app.match(/function monitorSafetyForPreview\(\)[\s\S]*?\n}/)?.[0] || "";
  assert.doesNotMatch(safetyDecision, /return monitorSafetyDecision\([\s\S]*syncPlaybackAvailability/);
  assert.doesNotMatch(app, /elements\.playButton\.disabled = !state\.analysis/);
  assert.doesNotMatch(app, /elements\.transportSeek\.disabled = !state\.analysis/);
  assert.match(css, /\.assessment-selects select,[\s\S]*\.help-nav button \{ min-height: 44px; \}/);
  assert.match(css, /\.session-transport output,[\s\S]*\.monitor-safety-status \{ font-size: \.8125rem; \}/);
  assert.match(css, /\.legend-chip,[\s\S]*\.local-peak-card-fields label,[\s\S]*\.monitor-safety-status \{ font-size: \.8125rem; \}/);
});

test("toningar är valfria, flexibla och har stora iPad-reglage", () => {
  assert.match(html, /id="fadeInToggle"/);
  assert.match(html, /id="fadeOutToggle"/);
  assert.match(html, /id="fadeInNumber"[^>]+type="number"/);
  assert.match(html, /id="fadeOutNumber"[^>]+type="number"/);
  assert.match(html, /id="fadeInRange"[^>]+type="range"/);
  assert.match(html, /id="fadeOutRange"[^>]+type="range"/);
  assert.doesNotMatch(html, /id="fade(?:In|Out)Toggle"[^>]+checked/);
  assert.match(css, /\.fade-switch\s*\{[^}]*min-height:\s*44px/s);
  assert.match(css, /\.preset-row button\s*\{[^}]*min-height:\s*44px/s);
  assert.match(css, /\.nudge-group button\s*\{[^}]*min-height:\s*44px/s);
  assert.match(html, />−10 ms<|>\+10 ms</);
  for (const id of ["fadeProfileModeNotice", "gainProfileModeNotice", "enableEditedProfileForFadesButton", "enableEditedProfileForGainButton"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.equal((html.match(/>Aktivera Redigerad WAV-master</g) || []).length, 2);
  const exportProfile = app.match(/function setExportProfile\(profile, options = \{\}\)[\s\S]*?\n}\n\nfunction syncAuditionUi/)?.[0] || "";
  assert.match(exportProfile, /fadeProfileModeNotice/);
  assert.match(exportProfile, /gainProfileModeNotice/);
  assert.match(app, /enableEditedProfileForFadesButton[\s\S]*setExportProfile\("edited-wav"\)/);
  assert.match(app, /Ingen ljudändring har gjorts ännu/);
});

test("medhörningen schemalägger samma linjära fadefunktion med AudioParam", () => {
  const scheduler = app.match(/function schedulePreviewEnvelope[\s\S]*?\n}\n\nfunction updateMonitoringGraph/)?.[0] || "";
  assert.match(scheduler, /fadeEnvelopeAt/);
  assert.match(scheduler, /cancelScheduledValues/);
  assert.match(scheduler, /setValueAtTime/);
  assert.match(scheduler, /linearRampToValueAtTime/);
  assert.match(scheduler, /localGainFactorAtFrame/);
  assert.match(app, /function previewEnvelopeBreakpoints[\s\S]*localGainBreakpoints/);
  assert.doesNotMatch(scheduler, /requestAnimationFrame|setInterval/);
  assert.match(app, /fadeInFrames:\s*Math\.round\(state\.trim\.fadeInSeconds \* sampleRate\(\)\)/);
  assert.match(app, /fadeOutFrames:\s*Math\.round\(state\.trim\.fadeOutSeconds \* sampleRate\(\)\)/);
});

test("seriereferensen har tre uttryckliga steg och ingen dold toppsänkning", () => {
  assert.match(html, /id="calculateSeriesButton"[^>]*>Beräkna nivåförslag/);
  assert.match(html, /id="previewSeriesButton"[^>]*>Prova förslag/);
  assert.match(html, /id="applySeriesButton"[^>]*>Använd föreslagen global gain/);
  assert.match(html, /id="preserveSeriesButton"[^>]*>Bevara oförändrat/);
  assert.match(html, /-19 LUFS-I, acceptans -20 till -18 LUFS-I och -2 dBTP/);
  assert.match(html, /Ingen dold toppsänkning/);
  assert.match(html, /Redan klippt ljud repareras inte/);
});

test("exporten använder endast synlig global gain och sparar serieflödet", () => {
  assert.match(app, /series:\s*\{ status: "preserved"/);
  assert.match(app, /targetLufs:\s*TMH_SERIES_PROFILE\.targetLufs/);
  assert.match(app, /ceilingDbtp:\s*TMH_SERIES_PROFILE\.truePeakOrientationDbtp/);
  const seriesUi = app.match(/function syncSeriesUi\(\)[\s\S]*?\n}/)?.[0] || "";
  assert.match(seriesUi, /elements\.localPeakCeiling\.value = String\(deliveryCeiling\)/);
  assert.match(app, /profileVersion:\s*TMH_SERIES_PROFILE\.version/);
  const projectEdit = app.match(/function projectEdit\(\)[\s\S]*?\n}/)?.[0] || "";
  assert.match(projectEdit, /globalGainDb:\s*state\.trim\.gainDb/);
  assert.doesNotMatch(projectEdit, /peakHandling/);
  const exportCall = app.match(/exportWorker\.postMessage\([\s\S]*?\n\s*}\);/)?.[0] || "";
  assert.match(exportCall, /globalGainDb:\s*state\.trim\.gainDb/);
  assert.match(exportCall, /enforceTruePeakCeiling:\s*selectedProfile === "edited-wav"/);
  assert.match(exportCall, /truePeakCeilingDbtp:\s*state\.series\.ceilingDbtp/);
  assert.doesNotMatch(exportCall, /peakHandling/);
});

test("redigering ogiltigförklarar hela tidigare exportverifieringen", () => {
  const sharedInvalidation = app.match(/function invalidatePreflightAndVerification\([\s\S]*?\n}\n\nfunction markEditChanged/)?.[0] || "";
  const editInvalidation = app.match(/function markEditChanged\([^)]*\)[\s\S]*?\n}/)?.[0] || "";
  assert.match(sharedInvalidation, /state\.regionAnalysis = null/);
  assert.match(sharedInvalidation, /state\.verifiedExport = null/);
  assert.match(sharedInvalidation, /state\.lastExportReport = null/);
  assert.match(sharedInvalidation, /operation: "analyze-region"/);
  assert.match(sharedInvalidation, /state\.jobs\.region = null/);
  assert.match(sharedInvalidation, /\["running", "cancelling", "complete"\]\.includes\(state\.exportStatus\)/);
  assert.match(sharedInvalidation, /state\.jobs\.export = null/);
  assert.match(editInvalidation, /invalidatePreflightAndVerification\(\)/);
  assert.match(editInvalidation, /state\.spectralDiagnostics = null/);
  assert.match(editInvalidation, /operation: "spectral-diagnostics"/);
  assert.match(editInvalidation, /state\.jobs\.spectral = null/);
  assert.match(editInvalidation, /updateProjectedMetrics\(\)/);
  assert.match(editInvalidation, /updateExportRecommendation\(\)/);

  const report = app.match(/function reportInput\(\)[\s\S]*?\n}/)?.[0] || "";
  assert.match(report, /state\.exportStatus === "complete" && Boolean\(state\.verifiedExport\)/);
  assert.match(report, /verifiedExport: hasCurrentVerifiedExport \? state\.verifiedExport : null/);

  const exportStart = app.match(/function startExport\(\)[\s\S]*?\n}\n\nfunction handleExportMessage/)?.[0] || "";
  assert.match(exportStart, /state\.lastExportReport = null/);
  assert.match(exportStart, /state\.verifiedExport = null/);
  assert.match(exportStart, /renderPublicationCard\(\)/);
  const handler = app.match(/function handleAnalysisMessage\(data = \{\}\)[\s\S]*?\n}\n\nfunction finishAnalysisJob/)?.[0] || "";
  const regionCancelled = handler.match(/if \(operation === "region"\) \{ state\.regionStatus = "cancelled";[^\n]+/)?.[0] || "";
  const regionError = handler.match(/if \(operation === "region" && elements\.regionMeasureStatus\) \{ state\.regionStatus = "error";[^\n]+/)?.[0] || "";
  assert.match(regionCancelled, /renderDeepMeasurements\(\)/);
  assert.match(regionError, /renderDeepMeasurements\(\)/);
});

test("adaptiv detalj, previewkanaler och workerjobb är operabla", () => {
  assert.match(app, /type:\s*"waveform-detail"/);
  assert.match(app, /function bindTimelineGestures/);
  assert.match(app, /timelinePointers\.size === 2/);
  assert.match(app, /function configureMonitorRouting/);
  assert.match(app, /mode === "mono" \? 0\.5 : 1/);
  assert.match(html, /name="previewMode" value="source"/);
  assert.match(html, /name="previewMode" value="export"/);
  assert.match(html, /name="monitorMode" value="left"/);
  assert.match(html, /name="monitorMode" value="right"/);
  assert.match(html, /name="monitorMode" value="mono"/);
  assert.match(app, /function nextJobId/);
  assert.match(app, /function isCurrentJob/);
  assert.match(app, /tracks\.correlation/);
  assert.match(app, /timelines\.correlation/);
  assert.match(app, /KORR/);
  assert.match(html, /Vågform L och R, separata spår/);
  assert.match(html, /separata spår för vänster och höger kanal/);
  assert.match(app, /const laneTop = track\.top \+ track\.height \* channelIndex \/ channelCount/);
  assert.match(app, /channelCount === 1 \? "MONO" : channelIndex === 0 \? "L" : "R"/);
  assert.match(app, /context\.lineTo\(width, laneTop\)/);
  assert.match(css, /\.timeline-card\.is-timeline-expanded/);
  assert.match(css, /@media\(pointer:coarse\).*\.timeline-canvas\{touch-action:pan-y\}/);
  assert.doesNotMatch(css, /touch-action:none/);
  assert.match(css, /\.button-small\s*\{[^}]*min-height:\s*44px/s);
  assert.match(css, /\.legend-chip\s*\{[^}]*min-height:\s*44px/s);
  assert.match(app, /card\.setAttribute\("role", "dialog"\)/);
  assert.match(app, /card\.setAttribute\("aria-modal", "true"\)/);
  assert.match(app, /isolateExpandedTimeline\(card\)/);
  assert.match(app, /timelineFocusableElements\(expanded\)/);
  assert.match(app, /expandedTimelineRestoreFocus\.focus\(\)/);
  assert.match(html, /id="cancelAnalysisButton"/);
  assert.match(html, /id="cancelExportButton"/);
});

test("importerade markörtider normaliseras numeriskt före DOM-rendering", () => {
  const renderer = app.match(/function renderMarkers\(\)[\s\S]*?\n}\n\nfunction syncTrimUi/)?.[0] || "";
  assert.match(renderer, /finite\(marker\?\.seconds\)/);
  assert.match(renderer, /if \(seconds === null\) return null/);
  assert.match(renderer, /data-marker-jump="\$\{String\(marker\.seconds\)\}"/);
  assert.match(renderer, /escapeHtml\(marker\.text\)/);
  for (const field of ["endSeconds", "severity", "channel", "detail", "objective", "origin", "reviewStatus"]) assert.match(renderer, new RegExp(field));
});

test("mätkedja, canvastext och lokala arbetsfiler är synliga", () => {
  assert.match(html, />Källfil</);
  assert.match(html, />Beräknat exporturval</);
  assert.match(html, />Verifierad exportfil</);
  assert.match(html, /id="canvasTextAlternative"/);
  assert.match(html, /id="storedExportsList"/);
  assert.match(app, />Hämta igen</);
  assert.match(app, /item\.status \|\| "complete"/);
  assert.match(app, /item\.status === "partial" \? "Ofullständig kraschrest"/);
  assert.match(app, /const download = complete \?/);
  assert.match(app, /storage-list/);
  assert.match(app, /storage-get/);
  assert.match(app, /storage-remove/);
  assert.match(app, /storage-clear/);
  assert.match(html, /id="updateBanner"/);
  assert.match(app, /hasUnsafeUpdateState/);
});

test("poddflödet har publiceringskort, serieöversikt och handoff", () => {
  for (const id of ["publicationStatus", "publicationAutoChecks", "publicationExceptionNote", "exportEpisodeHandoffButton", "seriesReportsInput", "seriesOverviewResult", "runSpectralDiagnosticsButton"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(app, /function renderPublicationCard/);
  assert.match(app, /function exportEpisodeHandoff/);
  assert.match(app, /function importSeriesReports/);
  assert.match(app, /function episodeMasterFileName/);
  assert.match(app, /TMH_E\$\{episode\}_\$\{slug\}_MASTER\.wav/);
  assert.match(app, /state\.regionAnalysis\?\.processed\?\.summary/);
});
